// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function demonstrateUtilsImport(param) {
  var __x = import("@rescriptModule/Utils");
  __x.then(function (m) {
        console.log(Curry._2(m.add, 1, 2));
        return Promise.resolve(undefined);
      });
  
}

function App(Props) {
  return React.createElement("div", undefined, "Welcome to this fine, unstyled app. Use the buttons below to demonstrate dynamic imports.", React.createElement("div", undefined, React.createElement("button", {
                      onClick: (function (param) {
                          return demonstrateUtilsImport(undefined);
                        })
                    }, "Load and use Utils.res")));
}

var make = App;

export {
  demonstrateUtilsImport ,
  make ,
  
}
/* react Not a pure module */
