// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as React from "react";
import * as ReactDom from "react-dom";

ReactDom.render(React.createElement(App.make, {}), document.getElementById("root"));

export {
  
}
/*  Not a pure module */
